/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubredditDataRouteImport } from './routes/subreddit-data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSubredditRouteImport } from './routes/r.$subreddit'
import { Route as ApiRedditSubredditRouteImport } from './routes/api/reddit.$subreddit'
import { Route as ApiCronScrapeRouteImport } from './routes/api/cron/scrape'

const SubredditDataRoute = SubredditDataRouteImport.update({
  id: '/subreddit-data',
  path: '/subreddit-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditRoute = RSubredditRouteImport.update({
  id: '/r/$subreddit',
  path: '/r/$subreddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSubredditRoute = ApiRedditSubredditRouteImport.update({
  id: '/api/reddit/$subreddit',
  path: '/api/reddit/$subreddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScrapeRoute = ApiCronScrapeRouteImport.update({
  id: '/api/cron/scrape',
  path: '/api/cron/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subreddit-data': typeof SubredditDataRoute
  '/r/$subreddit': typeof RSubredditRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subreddit-data': typeof SubredditDataRoute
  '/r/$subreddit': typeof RSubredditRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subreddit-data': typeof SubredditDataRoute
  '/r/$subreddit': typeof RSubredditRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subreddit-data'
    | '/r/$subreddit'
    | '/api/cron/scrape'
    | '/api/reddit/$subreddit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subreddit-data'
    | '/r/$subreddit'
    | '/api/cron/scrape'
    | '/api/reddit/$subreddit'
  id:
    | '__root__'
    | '/'
    | '/subreddit-data'
    | '/r/$subreddit'
    | '/api/cron/scrape'
    | '/api/reddit/$subreddit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubredditDataRoute: typeof SubredditDataRoute
  RSubredditRoute: typeof RSubredditRoute
  ApiCronScrapeRoute: typeof ApiCronScrapeRoute
  ApiRedditSubredditRoute: typeof ApiRedditSubredditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subreddit-data': {
      id: '/subreddit-data'
      path: '/subreddit-data'
      fullPath: '/subreddit-data'
      preLoaderRoute: typeof SubredditDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit': {
      id: '/r/$subreddit'
      path: '/r/$subreddit'
      fullPath: '/r/$subreddit'
      preLoaderRoute: typeof RSubredditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/$subreddit': {
      id: '/api/reddit/$subreddit'
      path: '/api/reddit/$subreddit'
      fullPath: '/api/reddit/$subreddit'
      preLoaderRoute: typeof ApiRedditSubredditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scrape': {
      id: '/api/cron/scrape'
      path: '/api/cron/scrape'
      fullPath: '/api/cron/scrape'
      preLoaderRoute: typeof ApiCronScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubredditDataRoute: SubredditDataRoute,
  RSubredditRoute: RSubredditRoute,
  ApiCronScrapeRoute: ApiCronScrapeRoute,
  ApiRedditSubredditRoute: ApiRedditSubredditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
