/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRedditSubredditRouteImport } from './routes/api/reddit.$subreddit'
import { Route as ApiCronScrapeRouteImport } from './routes/api/cron/scrape'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSubredditRoute = ApiRedditSubredditRouteImport.update({
  id: '/api/reddit/$subreddit',
  path: '/api/reddit/$subreddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScrapeRoute = ApiCronScrapeRouteImport.update({
  id: '/api/cron/scrape',
  path: '/api/cron/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/cron/scrape': typeof ApiCronScrapeRoute
  '/api/reddit/$subreddit': typeof ApiRedditSubredditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/api/cron/scrape' | '/api/reddit/$subreddit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/api/cron/scrape' | '/api/reddit/$subreddit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/cron/scrape'
    | '/api/reddit/$subreddit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiCronScrapeRoute: typeof ApiCronScrapeRoute
  ApiRedditSubredditRoute: typeof ApiRedditSubredditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/$subreddit': {
      id: '/api/reddit/$subreddit'
      path: '/api/reddit/$subreddit'
      fullPath: '/api/reddit/$subreddit'
      preLoaderRoute: typeof ApiRedditSubredditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scrape': {
      id: '/api/cron/scrape'
      path: '/api/cron/scrape'
      fullPath: '/api/cron/scrape'
      preLoaderRoute: typeof ApiCronScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiCronScrapeRoute: ApiCronScrapeRoute,
  ApiRedditSubredditRoute: ApiRedditSubredditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
